import type {Metadata} from "next";
import {Space_Grotesk} from "next/font/google";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: '/pashas_portfolio/favicon.svg',
    },
};

const spaceGrotesk = Space_Grotesk({
    variable: '--font-space-grotesk',
    subsets: ['latin'],
    weight: ['400', '500', '700'],
});

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${spaceGrotesk.variable} antialiased`}>
        {children}
        </body>
        </html>
    );
}
